### ISSUE TITLE
Can't chisel gold back to vanilla gold block

### ISSUE THREAD

**Issue by Elysara** [scalda/Monsterpack#10]
When using the chisel mod's chisel on gold blocks there's no way to go back to the vanilla gold block with it.
![2018-02-19_11 04 22](https://user-images.githubusercontent.com/36612716/36386707-ac5d2dce-1564-11e8-8f4a-3b72b35179bc.png)

**Comment by scalda** [comment]
this is a known bug in the chisel and it seems to be being worked on but sadly won't out for the next version of the pack as soon as it's available for update I will implement the update.

looks like it's fixed in 1.12.2 but waiting on a 1.10.2 version

**Comment by scalda** [comment]
this should be fixed in the latest version of the pack if not please let me know or please close the issue if it is fixed?

**Comment by Elysara** [comment]
The issue is still happening in the latest version of the pack.

![2018-03-06_22 25 17](https://user-images.githubusercontent.com/36612716/37071984-4408534a-218d-11e8-9d11-f5e3a50e57f9.png)
